### ISSUE TITLE
Saying 'leadership' in the middle of the sentence shouldn't summon Bezos bot

### ISSUE THREAD

**Issue by shipitsteven** [jiangoz/JeffBezosBot#2]
**Unwanted behavior:** saying "leadership" in the middle of a sentence summons Bezos bot to interject with leadership principle site.

See screenshot:
![image](https://user-images.githubusercontent.com/62415298/168455627-5b60c25d-8504-402c-b814-2f2da8367fd9.png)

**Comment by jiangoz** [comment]
Changed to only trigger on "leadership principle". 
Removed link embed to be less intrusive.
